### ISSUE TITLE
why no iges support?

### ISSUE THREAD

**Issue by piaoger** [miho/OCC-CSG#6]
I wonder if you have known there are something wrong or just skip iges support.

I am trying to add iges support for occ-csg. However, I  always get "Segmentation fault" while exporting iges to stl. 

My environment: MacOSX & "brew install opencascade"

```
> loading geometry
 -> reading file '/Users/badman/models/iges/in/T26.IGS'
Total number of loaded entities 90416.
 -> done.
> saving geometry
 -> writing file '/Users/badman/models/output/k.stl'
 -> STL TOL: 0.5
Segmentation fault: 11
```

**Comment by piaoger** [comment]
I just tried a couple of very simple iges files and it works fine. I can create a PR for iges import/export for iges if you want.

**Comment by miho** [comment]
I skipped IGES support because I was under the impression that STEP is more reliable. But you are welcome to add IGES support as long as it works reasonably well.

**Comment by miho** [comment]
We just switched from OCE-0.18 to OCC 7.3.x. Maybe IGES works better now. Let me know if you want to try.

**Comment by piaoger** [comment]
Thanks for merging my [PR](https://github.com/miho/OCC-CSG/pull/7)
